-- MySQL Script generated by MySQL Workbench
-- Fri Mar  4 11:50:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dinodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dinodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dinodb` DEFAULT CHARACTER SET utf8 ;
USE `dinodb` ;

-- -----------------------------------------------------
-- Table `dinodb`.`dataset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dinodb`.`dataset` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(1000) NULL,
  `datapoint_price` INT NOT NULL,
  `datapoint_count` INT NOT NULL,
  `uploaded_at` VARCHAR(50) NOT NULL,
  `archived` BINARY(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dinodb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dinodb`.`user` (
  `id` VARCHAR(36) NOT NULL,
  `displayname` VARCHAR(50) NULL,
  `email` VARCHAR(250) NOT NULL,
  `is_admin` BINARY(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dinodb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dinodb`.`order` (
  `id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `state` VARCHAR(8) NOT NULL,
  `total` INT NOT NULL,
  `purchased_at` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_order_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `dinodb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dinodb`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dinodb`.`order_item` (
  `order_id` VARCHAR(36) NOT NULL,
  `dataset_id` VARCHAR(36) NOT NULL,
  `datapoint_count` INT NOT NULL,
  INDEX `fk_order_item_dataset_idx` (`dataset_id` ASC) VISIBLE,
  INDEX `fk_order_item_order1_idx` (`order_id` ASC) VISIBLE,
  PRIMARY KEY (`order_id`),
  CONSTRAINT `fk_order_item_dataset`
    FOREIGN KEY (`dataset_id`)
    REFERENCES `dinodb`.`dataset` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_item_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `dinodb`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dinodb`.`cart_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dinodb`.`cart_item` (
  `user_id` VARCHAR(36) NOT NULL,
  `dataset_id` VARCHAR(36) NOT NULL,
  `datapoint_count` VARCHAR(45) NOT NULL,
  INDEX `fk_cart_item_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_cart_item_dataset1_idx` (`dataset_id` ASC) VISIBLE,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_cart_item_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `dinodb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_item_dataset1`
    FOREIGN KEY (`dataset_id`)
    REFERENCES `dinodb`.`dataset` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
