version: "3"
services:
  dino-db:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: dino-mysql
    ports:
      - "3306:3306"
    networks:
      - dino-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dinodb

  dino-web:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: dino-spring
    ports:
      - "8080:8080"
    networks:
      - dino-net
    depends_on:
      - "dino-db"
    command: ["./wait-for-it.sh", "-t", "0", "dino-backend-dino-db-1:3306", "--", "java", "-jar", "dino.jar"]

networks:
  dino-net:
